Repository cdalvaro/docker-salt-master, pull requests merged in 2020-11, with the labels that each got.

#47 Ignore chown errors
  assets/runtime/functions.sh
Labels: bug, enhancement, good first issue

#46 Upgrade to v3002.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/linter.yml
  CHANGELOG.md
  Dockerfile
  README.md
  VERSION
  assets/runtime/functions.sh
  docker-compose.yml
Labels: cve-release, upgrade

#48 Upgrade to v3002.2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/build-and-test.yml
  .gitignore
  CHANGELOG.md
  Dockerfile
  README.md
  VERSION
  docker-compose.yml
Labels: upgrade
